### ISSUE TITLE
"Another operation is in progress" error when using transactions and asyncio.gather

### ISSUE THREAD

**Issue by jekel** [fantix/gino#313] opened 2018-08-21 11:28 UTC
Hello!
When i need to make several operations in parallel with db i'm using asyncio.gather with task and transaction inside it, but i have found that in GINO it does not work correctly - throws an error
`asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress`

How to reproduce it:
```python
    async def t():
        async with db.transaction():
            await Model.query.gino.first()

    await asyncio.gather(*[t() for i in range(5)])
```

If i will place db.acquire before db.transaction it does not change anything.

I think that problem is that there must be new real connection and transaction in it when using `asyncio.gather`

stacktrace
```   
 await Model.query.gino.first()
  File "venv/project/lib/python3.7/site-packages/gino/api.py", line 135, in first
    **params)
  File "venv/project/lib/python3.7/site-packages/gino/engine.py", line 681, in first
    return await conn.first(clause, *multiparams, **params)
  File "venv/project/lib/python3.7/site-packages/gino/engine.py", line 336, in first
    return await result.execute(one=True)
  File "venv/project/lib/python3.7/site-packages/gino/dialects/base.py", line 207, in execute
    context.statement, context.timeout, args, 1 if one else 0)
  File "venv/project/lib/python3.7/site-packages/gino/dialects/asyncpg.py", line 175, in async_execute
    query, executor, timeout)
  File "venv/project/lib/python3.7/site-packages/asyncpg/connection.py", line 1400, in _do_execute
    stmt = await self._get_statement(query, None)
  File "venv/project/lib/python3.7/site-packages/asyncpg/connection.py", line 323, in _get_statement
    statement = await self._protocol.prepare(stmt_name, query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
  File "asyncpg/protocol/protocol.pyx", line 675, in asyncpg.protocol.protocol.BaseProtocol._check_state
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress
```

* GINO version: 0.7.5
* Python version: 3.7.0
* asyncpg version: 0.17.0
* PostgreSQL version: 9.6.9
* Quart version 0.6.4

**Comment by jekel** [comment] 2018-08-21 15:33
So.. i have made investigation and found that without implicit connection passing all nested quieries are made not in connection of db.transaction :(

**Comment by fantix** [comment] 2018-08-22 09:09
Thanks for the report! I'm seeing two critical issues for GINO in Python 3.7:

1. Sub-tasks are able to share connections when any connection was acquired and released in main task before spawning sub-tasks.

```python
import asyncio
import gino

db = gino.Gino()


async def main():
    await db.set_bind('postgresql://localhost/gino')

    async with db.acquire():
        pass

    async def t():
        async with db.acquire(reuse=True):
            await db.scalar('SELECT now()')

    await asyncio.gather(*[t() for _ in range(5)])


asyncio.run(main())
```

2. In the same scenario, `db.acquire(reuse=False)` won't fail, but `db.transaction(reuse=False)` will.

**Comment by jekel** [comment] 2018-08-22 09:44
This error also is valid for python 3.6.

But with code like this, does not work also
```python
    async with db.transaction():
        pass

    async def t():
        async with db.transaction(reuse=True):
            await Model.get(...) 

    await asyncio.gather(*[t() for i in range(5)])
```

Is there anyway to use `db.acquire(reuse=False)` in all nested queries inside context block without passing any variables explicitly?

**Comment by fantix** [comment] 2018-08-24 06:48
> This error also is valid for python 3.6.

Could you please share your env and errors when above code fails in Python 3.6? I didn't reproduce in Python 3.6.

> Is there anyway to use db.acquire(reuse=False) in all nested queries inside context block without passing any variables explicitly?

FYI `db.acquire()` has `reuse=False` by default.

**Comment by jekel** [comment] 2018-08-29 10:13
@fantix You know, the same issue is also valid for Sanic
```python
import asyncio
from sanic import Sanic
from sanic.exceptions import abort
from sanic.response import json
from gino.ext.sanic import Gino

app = Sanic()
app.config.DB_DSN = '...'

db = Gino()
db.init_app(app)


class Model(db.Model):
    __tablename__ = 'model'

    id = db.Column(db.Integer, primary_key=True)


@app.route("/test")
async def test(request):
    async def t():
        async with db.transaction():
            await Model.get_or_404(...)
    await asyncio.gather(*[t() for i in range(5)])
    return json({})


if __name__ == '__main__':
    app.run(debug=True)
```
```  
    async with db.transaction():
  File "/venv//lib/python3.7/site-packages/gino/engine.py", line 168, in __aenter__
    return await self._tx_ctx.__aenter__()
  File "/venv//lib/python3.7/site-packages/gino/transaction.py", line 166, in __aenter__
    await self._begin()
  File "/venv//lib/python3.7/site-packages/gino/transaction.py", line 81, in _begin
    await self._tx.begin()
  File "/venv//lib/python3.7/site-packages/gino/dialects/asyncpg.py", line 238, in begin
    await self._tx.start()
  File "/venv//lib/python3.7/site-packages/asyncpg/transaction.py", line 138, in start
    await self._connection.execute(query)
  File "/venv//lib/python3.7/site-packages/asyncpg/connection.py", line 273, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 317, in query
  File "asyncpg/protocol/protocol.pyx", line 675, in asyncpg.protocol.protocol.BaseProtocol._check_state
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

```

**Comment by fantix** [comment] 2018-08-29 10:15
Yes thanks, all web framework plugins in GINO enabled inherit. I'm trying to make that a default in upstream contextvars PEP-567 backport.

**Comment by wwwjfy** [comment] 2018-09-02 14:45
It doesn't matter whether the connection was acquired and released in the main task. It also happens in the following code:

```python
import asyncio
import gino

db = gino.Gino()


async def main():
    await db.set_bind('postgresql://localhost/gino')

    async with db.acquire():
        async def t():
            async with db.acquire(reuse=True):
                print(await db.scalar('SELECT now()'))

        await asyncio.gather(*[t() for _ in range(5)])


asyncio.run(main())
```

The issue is with `db.acquire()` happening before subtasks start, they share the common context `stack`, in which case the subsequent tasks get the same connection pushed by the first task.

I don't have a clear answer in mind if gino should create a new connection, or have a lock-like mechanism on the connection. I assume there are valid use cases in both scenarios.

**Comment by wwwjfy** [comment] 2018-09-04 04:44
@fantix That can fix the problem raised, but can't prevent that the same reused connection got by subtasks, like the snippet in my previous comment. Because `scalar` has `self.acquire(reuse=True)`, if the connection is being used by another subtask, the exception will be thrown.

**Comment by fantix** [comment] 2018-09-04 06:41
Ah, first of all, context should be inherited in subtasks, this was discussed in #84, [PEP-550](https://www.python.org/dev/peps/pep-0550/#coroutines-and-asynchronous-tasks):

> The main reason for why tasks inherit the context, and threads do not, is the common usage intent. Tasks are often used for relatively short-running operations which are logically tied to the code that spawned the task (like running a coroutine with a timeout in asyncio). OS threads, on the other hand, are normally used for long-running, logically separate code.

and eventually implemented in [PEP-567](https://www.python.org/dev/peps/pep-0567/#asyncio):

> Tasks in asyncio need to maintain their own context that they inherit from the point they were created at.

Regarding shared connections, I think it should follow the way contexts are inherited, so that people don't have to remember another rule. Therefore if users are spawning subtasks within an `async with db.acquire()` context, they should be responsible for causing such error.

In your example, if user was in doubt whether the reusing connection may be accessed concurrently, an explicit `reuse=False` should always be present. But in case of this:

```python
async def main():
    async with db.acquire():
        await asyncio.wait_for(db.status('SELECT pg_sleep(10)'), 1)
```

`db.status()` should reuse the connection explicitly acquired previously, even if `asyncio.wait_for()` puts it into a subtask.

Hopefully this explains. 😃

**Comment by wwwjfy** [comment] 2018-09-04 07:57
I have no issues on context inheritance, but not sure if there is any case user wants to use only one connection for those subtasks or in one request, where we'll need to lock-release it.

**Comment by fantix** [comment] 2018-09-04 08:13
Ah, got it. I think the users should lock-release it themselves manually, likewise, asyncpg didn't provide locking either.

**Comment by fantix** [comment] 2018-09-04 08:26
No it's not - I'm trying to remove `aiocontextvars.ContextVar.delete()` and honor `contextvars.ContextVar.reset(token)`.

**Closed** 2018-09-13 02:12 UTC
Labels: bug

**Comment by fantix** [comment] 2018-09-30 02:07
Guess this should be backported to GINO 0.7 without introducing aiocontextvars 0.2.

**Comment by skandalfo** [comment] 2018-10-07 23:35
Wow.

I just found that the fixes for this (the upcoming 0.8.0 with aiocontextvars 0.2?) likely also fix my woes with transactions.

I'm explicitly not using the aiohttp integration because the web part is just one side of my application, that also reacts to external events, so I didn't have the enable_inherit call anywhere. Long story short, whenever I used asyncio.gather to fork execution from within a transaction context, the current connection wouldn't be reused, so each of the coroutines I ran gather on used their own, transaction-less one, and I got plenty of "race conditions" that I was counting on the serializable isolation level to prevent.

I got to this by looking at PostgreSQL's statement logs where I couldn't see savepoints that I expected nested transactions to trigger. I dug all the code up to asyncpg's transaction support to verify they should be there. Eventually realized by the PIDs in the logs that different connections were in use when there should be only one.

I've just checked against master head, and now I see shared connections and nested savepoints, so I expect I'll see serialization failure retries now :-)

BTW. This is running on Python 3.5.3, and I made sure to have aiocontextvars imported before creating any loops.

**Comment by wwwjfy** [comment] 2018-10-08 02:30
Glad you find it works. One thing I'm thinking is using `asyncio.gather`, if it's used in your issue description, different coroutines share the same connection. This may cause nested transactions conflict with each other.
I don't use nested transactions much. This may not be true. I'll try it later.

**Comment by skandalfo** [comment] 2018-10-08 06:34
@wwwjfy you're right; I had not thought of different nested transactions being started in different branches. That's not going to work.

But I don't need them. I just need to know if a transaction is already active (and let it retry as a whole if it fails) or not (and create a new root one in the spot).

I'll likely upgrade my decorator to use aiocontextvars to implement that behavior rather than blindly starting a new (sub) transaction. That will also allow me to register actions to be run once a transaction has been irreversibly committed.

But losing the current connection just because I used asyncio.gather was completely unexpected.
